Interactive pull request
alicemirigo92/To-do-list pull request #3
Opened 2023-01-28 06:08 UTC by alicemirigo92

- [ ] Add event listener to the checkbox
- [ ] Implement a function

2023-01-28 06:37 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @alicemirigo92 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Update to-do completed status 📌 
✔️ Clear completed tasks 📌 
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 06:37 UTC, codepantha commented on src/modules/clear.js
> +  }
- [ ] The indexes of the todos are not correctly updated after clearing the completed to-do items. Please implement this change as it messes up the order of the items.
![image](https://user-images.githubusercontent.com/46839548/215250824-899d5152-e622-4c1e-b366-e8d76fe98aab.png)

2023-01-28 08:23 UTC, AmaduKamara approved these changes
# Status: Approved 🟢 🟢 🟢

Hi @alicemirigo92,

Good job working on the changes asked by the previous reviewer 👍🏽

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:
✅ You used Gitflow correctly 👍🏽 
✅ Linter checks passed 👍🏽
✅ Todo list is interactive as expected 👍🏽
✅ Todo items are indexed correctly 👍🏽

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-28 08:25 UTC, merged

2023-02-07 07:13 UTC, Divinity-dev commented on src/modules/check.js
> -// }
This part of your code should be removed to make a cleaner code

2023-02-07 07:13 UTC, Divinity-dev commented on src/modules/clear.js
> -//   }
remove this part too

2023-02-07 07:14 UTC, Divinity-dev commented on src/modules/clear.js
> -// }
Remove this part too

2023-02-07 07:20 UTC, Divinity-dev reviewed
Great work you've put into this project so far, just a little change. All commented out codes should be removed to make your code neater.